# Generated by Django 4.0.4 on 2022-07-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Website',
            new_name='websites',
        ),
    ]
