# Generated by Django 4.0.4 on 2022-07-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_website_car_websites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='price',
        ),
        migrations.AddField(
            model_name='website',
            name='link',
            field=models.CharField(default='https://', help_text='Please enter the full URL to the website.', max_length=200),
        ),
    ]
